<?php
$title = 'Reports & Analytics';
ob_start();
$user = $_SESSION['user'];
?>

<div class="row">
    <div class="col-md-12">
        <h2><i class="fas fa-chart-bar"></i> Reports & Analytics</h2>
        <p class="text-muted">Generate insights and reports for better mental health outcomes.</p>
    </div>
</div>

<div class="row mt-4">
    <div class="col-md-3">
        <div class="card text-center">
            <div class="card-body">
                <i class="fas fa-calendar-check fa-2x text-primary mb-2"></i>
                <h6>Session Reports</h6>
                <a href="/reports/generate?type=session" class="btn btn-outline-primary btn-sm">Generate</a>
            </div>
        </div>
    </div>
    <?php if ($user['role_name'] === 'patient'): ?>
        <div class="col-md-3">
            <div class="card text-center">
                <div class="card-body">
                    <i class="fas fa-heart fa-2x text-success mb-2"></i>
                    <h6>Mood Analytics</h6>
                    <a href="/reports/generate?type=mood" class="btn btn-outline-success btn-sm">Generate</a>
                </div>
            </div>
        </div>
    <?php endif; ?>
    <?php if ($user['role_name'] === 'therapist' || $user['role_name'] === 'admin'): ?>
        <div class="col-md-3">
            <div class="card text-center">
                <div class="card-body">
                    <i class="fas fa-users fa-2x text-info mb-2"></i>
                    <h6>Patient Reports</h6>
                    <a href="/reports/generate?type=patient" class="btn btn-outline-info btn-sm">Generate</a>
                </div>
            </div>
        </div>
    <?php endif; ?>
    <?php if ($user['role_name'] === 'admin'): ?>
        <div class="col-md-3">
            <div class="card text-center">
                <div class="card-body">
                    <i class="fas fa-shield-alt fa-2x text-warning mb-2"></i>
                    <h6>Audit Reports</h6>
                    <a href="/reports/generate?type=audit" class="btn btn-outline-warning btn-sm">Generate</a>
                </div>
            </div>
        </div>
    <?php endif; ?>
</div>

<div class="row mt-4">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <h5><i class="fas fa-history"></i> Recent Reports</h5>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>Report Type</th>
                                <th>Title</th>
                                <th>Generated By</th>
                                <th>Date</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            <!-- Sample data - in real app, this would come from database -->
                            <tr>
                                <td><span class="badge bg-primary">Session</span></td>
                                <td>Monthly Session Summary</td>
                                <td><?php echo $user['first_name'] . ' ' . $user['last_name']; ?></td>
                                <td><?php echo date('M j, Y'); ?></td>
                                <td>
                                    <button class="btn btn-sm btn-outline-primary" disabled>
                                        <i class="fas fa-download"></i> Download
                                    </button>
                                </td>
                            </tr>
                            <?php if ($user['role_name'] === 'patient'): ?>
                                <tr>
                                    <td><span class="badge bg-success">Mood</span></td>
                                    <td>Weekly Mood Analysis</td>
                                    <td><?php echo $user['first_name'] . ' ' . $user['last_name']; ?></td>
                                    <td><?php echo date('M j, Y', strtotime('-1 day')); ?></td>
                                    <td>
                                        <button class="btn btn-sm btn-outline-success" disabled>
                                            <i class="fas fa-download"></i> Download
                                        </button>
                                    </td>
                                </tr>
                            <?php endif; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<?php
$content = ob_get_clean();
require __DIR__ . '/../layout.php';
?>